#!/usr/bin/env python3

# Import required Python code.
import roslib
import rospy

from field_publisher_node.main import FieldPublisherNode

NODE_NAME = 'field_publisher_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = FieldPublisherNode()
    except rospy.ROSInterruptException:
        pass
